### ISSUE TITLE
Cannot start release 01.06, no main manifest

### ISSUE THREAD

**Issue by haug-den-lucas** [cloudsftp/HexSweeper#28]
Cannot start the new release.
Trying to run the jar version throws the following error:

```
E:\...\Downloads>java -jar desktop-HEX.01.06.jar
no main manifest attribute, in desktop-HEX.01.06.jar
```

Exe doesn't start either.

Java v12.0.1

**Comment by cloudsftp** [comment]
Launch4j is not configured properly.
I'm on it.
